tasks:
  - name: velero-package
    actions:
      - description: Deploy the UDS Velero Zarf Package
        cmd: zarf package deploy zarf-package-velero-${UDS_ARCH}-*.tar.zst --confirm --no-progress

  - name: velero-test-bundle
    actions:
      - description: Deploy the UDS bundle with Velero and its dependencies
        cmd: UDS_CONFIG=bundle/uds-config.yaml uds deploy bundle/uds-bundle-velero-test-${UDS_ARCH}-*.tar.zst --confirm --no-progress
