variables:
  dev-minio:
    buckets: |
      - name: velero
  velero:
   VELERO_BUCKET_PROVIDER_URL: "http://minio.dev-minio.svc.cluster.local:9000"
   VELERO_BUCKET: "velero"
   VELERO_BUCKET_REGION: "minio-region"
